        LDA ANTALL
        SUB EN
        STA AKKUMULATOR 
        INP 
        STA INPUT
        SUB PLUEPLE
        BRZ EPLE
        LDA INPUT
        SUB PLUBANAN
        BRZ BANAN
LOOP    LDA SUM
        ADD PRIS
        STA SUM
        LDA AKKUMULATOR
        SUB EN
        STA AKKUMULATOR
        BRP LOOP
        LDA SUM
        OUT
        HLT
EPLE    LDA PRISEPLE
        STA PRIS
        BRA LOOP
BANAN   LDA PRISBANAN
        STA PRIS
        BRA LOOP
PLUEPLE DAT 33
PRISEPLE DAT 10
PLUBANAN DAT 32
PRISBANAN DAT 7
INPUT   DAT 0
PRIS    DAT 0
ANTALL  DAT 19
EN      DAT 1
SUM     DAT 0
AKKUMULATOR DAT 0
 
